name: murAPI
main: me.jdog.murapi.MurAPI
version: ${project.version}
authors: [Muricans]
description: ${project.description}
website: ${project.url}
loadbefore: [MSG,Punish,Report,Staff]
commands:
  murapi:
    usage: /<command>
    description: plugin info
    permission: murapi.murapi
    permission-message: §cNo permission.
    aliases: [mur]