name: murAPI
main: me.jdog.murapi.MurAPI
version: 1.5
loadbefore: [MSG,Punish,Report]
commands:
  murapi:
    usage: /<command>
    description: plugin info
    permission: murapi.murapi
    permission-message: §cNo permission.
    aliases: [mur]