name: murAPI
main: me.jdog.murapi.MurAPI
version: 1.1.0
authors: [Muricans]
description: API I use for my plugins.
website: https://commonly.github.io
loadbefore: [MSG,Punish,Report,Staff]
commands:
  murapi:
    usage: /<command>
    description: plugin info
    permission: murapi.murapi
    permission-message: §cNo permission.
    aliases: [mur]